2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = BTCUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = ETHUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = BCHUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = XRPUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = EOSUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = LTCUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = TRXUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = ETCUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = LINKUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = XLMUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = ADAUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = XMRUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = DASHUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = ZECUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = XTZUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = BNBUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = ATOMUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = ONTUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = IOTAUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = BATUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = VETUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = NEOUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = QTUMUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = IOSTUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = THETAUSDT
2023-10-27 11:31 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 99, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 198, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 160, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 6202, in futures_klines
    return self._request_futures_api('get', 'klines', data=params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

2023-10-27 11:31 ERROR symbol = ALGOUSDT
2023-10-27 13:35 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-27 13:35 ERROR symbol = DEFIUSDT
2023-10-27 18:12 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-27 18:12 ERROR symbol = BTCDOMUSDT
2023-10-27 22:39 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-27 22:39 ERROR symbol = FOOTBALLUSDT
2023-10-27 23:22 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-27 23:22 ERROR symbol = BLUEBIRDUSDT
2023-10-28 03:04 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-28 03:04 ERROR symbol = BLURUSDT
2023-10-28 04:50 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-28 04:50 ERROR symbol = DODOXUSDT
2023-10-28 05:57 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-28 05:57 ERROR symbol = BIGTIMEUSDT
2023-10-28 06:06 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-28 06:06 ERROR symbol = ORBSUSDT
2023-10-28 06:29 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 100, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\DataProvider.py", line 63, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceDate.download(
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 212, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Major\custom.py", line 75, in historicalklines
    first_valid_ts = client._get_earliest_valid_timestamp(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 955, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 934, in _klines
    return self.get_klines(**params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 919, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2023-10-28 06:29 ERROR symbol = BSVUSDT
